apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tomcat
  namespace: tomcat
spec:
  secretName: tomcat-tls-staging
  issuerRef:
    name: tomcat-letsncrypt-staging
  # commonName: myapp.newtech.academy
  commonName: tomcat.psamman.com
  #dnsNames:
  #- www.myapp.newtech.academy
  acme:
    config:
    - http01:
        # namespace: tomcat
        ingress: tomcat
      domains:
      #- myapp.newtech.academy
      - tomcat.psamman.com
      #- www.myapp.newtech.academy
